server:
  port: 8080

spring:
  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcurl: jdbc:mysql://42.194.163.249:3307/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    salve:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcurl: jdbc:mysql://42.194.163.249:3308/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://42.194.163.249:3307/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*Mapper.xml
  type-aliases-package: com.gjz.test.**.domain
