server:
  port: 8080

orm:
  datasources:
    main:
      jdbc.driverClassName: com.mysql.jdbc.Driver
      jdbc.url: jdbc:mysql://42.194.163.249:3306/test?useUnicode=true&characterEncoding=UTF-8
      jdbc.username: test
      jdbc.password: 123456