server:
  port: 8080

spring:
  shardingsphere:
    datasource:
      names: test0,test1
      master:
        type: "com.alibaba.druid.pool.DruidDataSource"
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://42.194.163.249:3307/test0"
        username: root
        password: 123456
      slave:
        type: "com.alibaba.druid.pool.DruidDataSource"
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://42.194.163.249:3307/test1"
        username: root
        password: 123456
    props:
      sql:
        show: true
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: test$->{id % 2}
      tables:
        t_order:
          actual-data-nodes: test$->{0..1}.t_order$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_order$->{order_id % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
      binding-tables: t_order
      broadcast-tables: t_config


mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
