server:
  port: 8080

spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: "com.alibaba.druid.pool.DruidDataSource"
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://42.194.163.249:3307/test?useUnicode=true&characterEncoding=utf-8&useSSL=false"
        username: root
        password: 123456
      slave:
        type: "com.alibaba.druid.pool.DruidDataSource"
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://42.194.163.249:3308/test?useUnicode=true&characterEncoding=utf-8&useSSL=false"
        username: root
        password: 123456
    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true


mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
